version: '3'

tasks:
  default:
    desc: Build the ws binary
    deps: [build]

  build:
    desc: Build the ws binary
    cmds:
      - cargo build --release
      - mkdir -p bin
      - cp target/release/ws bin/ws
    sources:
      - src/**/*.rs
      - Cargo.toml
      - Cargo.lock
    generates:
      - bin/ws

  test:
    desc: Run all tests
    cmds:
      - cargo test -- --test-threads=1

  lint:
    desc: Run clippy
    cmds:
      - cargo clippy -- -D warnings

  fmt:
    desc: Format Rust code
    cmds:
      - cargo fmt

  fmt-check:
    desc: Check Rust code formatting (fails if unformatted)
    cmds:
      - cargo fmt --check

  clean:
    desc: Remove build artifacts
    cmds:
      - cargo clean
      - rm -rf bin/

  install:
    desc: Install ws via cargo
    cmds:
      - cargo install --path .

  check:
    desc: Run fmt, lint, and test
    cmds:
      - task: fmt
      - task: lint
      - task: test

  ci:
    desc: Run all CI checks (fmt-check, lint, build, test)
    cmds:
      - task: fmt-check
      - task: lint
      - task: build
      - task: test
