.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH wsp-describe 1  "describe " 
.SH NAME
describe \- Set or update a workspace description
.SH SYNOPSIS
\fBdescribe\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIworkspace\fR> <\fItext\fR> 
.SH DESCRIPTION
Set or update a workspace description
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIworkspace\fR>

.TP
<\fItext\fR>

