.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH wsp-template-show 1  "show " 
.SH NAME
show \- Show template contents [read\-only]
.SH SYNOPSIS
\fBshow\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIname\fR> 
.SH DESCRIPTION
Show template contents [read\-only]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIname\fR>

