.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH wsp-diff 1  "diff " 
.SH NAME
diff \- Show git diff across workspace repos [read\-only]
.SH SYNOPSIS
\fBdiff\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIworkspace\fR] [\fIargs\fR] 
.SH DESCRIPTION
Show git diff across workspace repos [read\-only]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIworkspace\fR]

.TP
[\fIargs\fR]

