.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH wsp-completion 1  "completion " 
.SH NAME
completion \- Output shell integration (completions + wrapper function) [read\-only]
.SH SYNOPSIS
\fBcompletion\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIshell\fR> 
.SH DESCRIPTION
Output shell integration (completions + wrapper function) [read\-only]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIshell\fR>

.br
[\fIpossible values: \fRzsh, bash, fish]
