.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH wsp-rename 1  "rename " 
.SH NAME
rename \- Rename a workspace, its directory, and git branches
.SH SYNOPSIS
\fBrename\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIold\fR> <\fInew\fR> 
.SH DESCRIPTION
Rename a workspace, its directory, and git branches
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIold\fR>

.TP
<\fInew\fR>

