.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH wsp-repo-rm 1  "rm " 
.SH NAME
rm \- Remove repo(s) from the current workspace
.SH SYNOPSIS
\fBrm\fR [\fB\-f\fR|\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIrepos\fR> 
.SH DESCRIPTION
Remove repo(s) from the current workspace
.SH OPTIONS
.TP
\fB\-f\fR, \fB\-\-force\fR
Remove even if repos have pending changes or unmerged branches
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIrepos\fR>

