.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH wsp-registry-rm 1  "rm " 
.SH NAME
rm \- Remove a repository and its mirror
.SH SYNOPSIS
\fBrm\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIname\fR> 
.SH DESCRIPTION
Remove a repository and its mirror
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIname\fR>

