.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH wsp-config-set 1  "set " 
.SH NAME
set \- Set a config value
.SH SYNOPSIS
\fBset\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIkey\fR> <\fIvalue\fR> 
.SH DESCRIPTION
Set a config value
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIkey\fR>

.TP
<\fIvalue\fR>

