.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH wsp-template-new 1  "new " 
.SH NAME
new \- Create a new template
.SH SYNOPSIS
\fBnew\fR [\fB\-\-from\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIname\fR> [\fIrepos\fR] 
.SH DESCRIPTION
Create a new template
.SH OPTIONS
.TP
\fB\-\-from\fR
Create from a workspace name or template file path
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIname\fR>

.TP
[\fIrepos\fR]
Repo URLs for the template
