.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH wsp-template-export 1  "export " 
.SH NAME
export \- Export a template to a file or stdout [read\-only]
.SH SYNOPSIS
\fBexport\fR [\fB\-\-stdout\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIname\fR> 
.SH DESCRIPTION
Export a template to a file or stdout [read\-only]
.SH OPTIONS
.TP
\fB\-\-stdout\fR
Print to stdout instead of writing a file
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIname\fR>

