.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH wsp-exec 1  "exec " 
.SH NAME
exec \- Run a command in each repo of a workspace
.SH SYNOPSIS
\fBexec\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIworkspace\fR> <\fIcommand\fR> 
.SH DESCRIPTION
Run a command in each repo of a workspace
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIworkspace\fR>

.TP
<\fIcommand\fR>

