.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH wsp-group-update 1  "update " 
.SH NAME
update \- Add or remove repos from a group
.SH SYNOPSIS
\fBupdate\fR [\fB\-\-add\fR] [\fB\-\-remove\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIname\fR> 
.SH DESCRIPTION
Add or remove repos from a group
.SH OPTIONS
.TP
\fB\-\-add\fR

.TP
\fB\-\-remove\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIname\fR>

