.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH wsp-st 1  "st " 
.SH NAME
st \- Git status across workspace repos [read\-only]
.SH SYNOPSIS
\fBst\fR [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIworkspace\fR] 
.SH DESCRIPTION
Git status across workspace repos [read\-only]
.SH OPTIONS
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Show per\-repo file lists
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIworkspace\fR]

