.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH wsp-log 1  "log " 
.SH NAME
log \- Show commits ahead of upstream per workspace repo [read\-only]
.SH SYNOPSIS
\fBlog\fR [\fB\-\-oneline\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIworkspace\fR] [\fIargs\fR] 
.SH DESCRIPTION
Show commits ahead of upstream per workspace repo [read\-only]
.SH OPTIONS
.TP
\fB\-\-oneline\fR
Flat chronological view across all repos
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIworkspace\fR]

.TP
[\fIargs\fR]

