.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH wsp 1  "wsp 0.7.0 (v0.7.0-48-g2ce74be-dirty)" 
.SH NAME
wsp \- Multi\-repo workspace manager
.SH SYNOPSIS
\fBwsp\fR [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Multi\-repo workspace manager
.SH OPTIONS
.TP
\fB\-\-json\fR
Output as JSON
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
wsp\-new(1)
Create a new workspace
.TP
wsp\-rm(1)
Remove a workspace
.TP
wsp\-ls(1)
List active workspaces [read\-only]
.TP
wsp\-st(1)
Git status across workspace repos [read\-only]
.TP
wsp\-diff(1)
Show git diff across workspace repos [read\-only]
.TP
wsp\-log(1)
Show commits ahead of upstream per workspace repo [read\-only]
.TP
wsp\-sync(1)
Fetch and rebase/merge all workspace repos
.TP
wsp\-exec(1)
Run a command in each repo of a workspace
.TP
wsp\-cd(1)
Change directory into a workspace
.TP
wsp\-recover(1)
List or restore recently removed workspaces [read\-only without args]
.TP
wsp\-rename(1)
Rename a workspace, its directory, and git branches
.TP
wsp\-describe(1)
Set or update a workspace description
.TP
wsp\-repo(1)
Manage repos in the current workspace
.TP
wsp\-registry(1)
Manage the global repo registry
.TP
wsp\-group(1)
Manage repo groups (deprecated, use `wsp template`)
.TP
wsp\-template(1)
Manage workspace templates
.TP
wsp\-config(1)
Manage wsp settings
.TP
wsp\-completion(1)
Output shell integration (completions + wrapper function) [read\-only]
.TP
wsp\-help(1)
Print this message or the help of the given subcommand(s)
.SH EXTRA
Workspace:
  new         Create a new workspace
  repo        Manage repos in the current workspace
  cd          Change directory into a workspace
  ls          List active workspaces [read\-only] [aliases: list]
  rename      Rename a workspace, its directory, and git branches
  describe    Set or update a workspace description
  rm          Remove a workspace [aliases: remove]
  recover     List or restore recently removed workspaces [read\-only without args]

Workflow:
  st          Git status across workspace repos [read\-only] [aliases: status]
  diff        Show git diff across workspace repos [read\-only]
  log         Show commits ahead of upstream per workspace repo [read\-only]
  sync        Fetch and rebase/merge all workspace repos
  exec        Run a command in each repo of a workspace

Admin:
  registry    Manage the global repo registry
  group       Manage repo groups (deprecated, use `wsp template`)
  template    Manage workspace templates
  config      Manage wsp settings
  completion  Output shell integration (completions + wrapper function) [read\-only]
.SH VERSION
v0.7.0 (v0.7.0\-48\-g2ce74be\-dirty)
